# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6

jobs:
  build:
    machine: true
    # machine:
    #   image: ubuntu-1604:201903-01
    # docker:
      # specify the version you desire here
      # - image: rundeck/ci@sha256:85ce247940c39bcb77794778c2b7aa02feabfa1a37036b88942bc0c1235495f2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # GRADLE_OPTS: -Xmx512m -XX:MaxPermSize=192m -Xss50m
      # _JAVA_OPTIONS: "-Xmx512m -Xms200m -Xss50m"
      TERM: dumb

    steps:
      - checkout
      # - setup_remote_docker
      # - run: ./gradlew --no-daemon --max-workers 2 -x check install --stacktrace --info
      # - run: ./gradlew --no-daemon --max-workers 2 test --stacktrace --info
      - run: nvm install 8 && echo 'nvm use 8' >> $BASH_ENV
      - run: ./gradlew --no-daemon -x check install --stacktrace --info
      - run: ./gradlew --no-daemon test --stacktrace --info
      # - run: groovy testbuild.groovy --buildType=development
      # - docker-publish/check
      # - run: ./gradlew docker:officialPush
