# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
  node: circleci/node@1.1.6

jobs:
  build:
    # machine: true
    # machine:
    #   image: ubuntu-1604:201903-01
    docker:
      # specify the version you desire here
      - image: rundeck/ci@sha256:85ce247940c39bcb77794778c2b7aa02feabfa1a37036b88942bc0c1235495f2

    resource_class: large

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      GRADLE_OPTS: -Xmx512m -XX:MaxPermSize=192m -Xss50m
      _JAVA_OPTIONS: "-Xmx512m -Xms200m -Xss50m"
      BASH_ENV: ~/.bashrc
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      # - run: ./gradlew --no-daemon --max-workers 2 test --stacktrace --info
      # - node/install-node:
      #     version: '8.13.0'
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      # - run: ./gradlew --no-daemon -x check install --stacktrace --info
      - run: ./gradlew --no-daemon --max-workers 4 -x check install --stacktrace --info --parallel
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .BuildNum }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ .BuildNum }}
      # - run: groovy testbuild.groovy --buildType=development
      # - docker-publish/check
      # - run: ./gradlew docker:officialPush

  test-gradle:
    machine: true

    working_directory: ~/repo

    environment:
      TERM: dumb
    
    steps:
      - checkout
      - node/install-node:
          version: '8.13.0'
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .BuildNum }}
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle" }}-{{ .BuildNum }}
            - v1-gradle-cache-{{ checksum "build.gradle" }}-
      - run: ./gradlew --no-daemon test --stacktrace --info
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-gradle:
          requires: [build]
